_prefs: 
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -4.5263671875
  - 53.91081008725409
  - 6
description: Tilemill 2 Map Style based on a Carboard look
format: "png8:m=h"
interactivity_layer: ''
maxzoom: 22
minzoom: 0
mtime: 1375998649857
name: Cardboard Map
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v3"
styles: 
  - style.mss
  - labels.mss
template: ''
