_prefs: 
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -6.8198
  - 57.3117
  - 10
description: Tilemill 2 Map Style based on a Carboard look
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: Cardboard Map
source: "mapbox:///mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - labels.mss
template: ''
