_prefs: 
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -4.866943359375
  - 54.23955053156177
  - 6
description: Tilemill 2 Map Style based on a Carboard look
format: "png8:m=h"
interactivity_layer: ''
maxzoom: 22
minzoom: 0
mtime: 1376034295471
name: Cardboard Map
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v3"
styles: 
  - style.mss
  - labels.mss
template: ''
