_prefs: 
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -10.43701171875
  - 56.078167004692844
  - 6
description: Tilemill 2 Map Style based on a Paperboard look
format: "png8:m=h"
interactivity_layer: ''
maxzoom: 22
minzoom: 0
mtime: 1375954257423
name: Paperboard Map
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v3"
styles: 
  - style.mss
  - labels.mss
template: ''
